/**
 *
 * $Id$
 */
package org.plcopen.xml.tc60201.validation;

import javax.xml.datatype.XMLGregorianCalendar;

import org.plcopen.xml.tc60201.AddData;
import org.plcopen.xml.tc60201.AddDataInfo;
import org.plcopen.xml.tc60201.CoordinateInfoType;

/**
 * A sample validator interface for {@link org.plcopen.xml.tc60201.ContentHeaderType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContentHeaderTypeValidator {
	boolean validate();

	boolean validateComment(String value);
	boolean validateCoordinateInfo(CoordinateInfoType value);
	boolean validateAddDataInfo(AddDataInfo value);
	boolean validateAddData(AddData value);
	boolean validateAuthor(String value);
	boolean validateLanguage(String value);
	boolean validateModificationDateTime(XMLGregorianCalendar value);
	boolean validateName(String value);
	boolean validateOrganization(String value);
	boolean validateVersion(String value);
}
