/**
 *
 * $Id$
 */
package org.plcopen.xml.tc60201.validation;

import org.plcopen.xml.tc60201.FbdType;
import org.plcopen.xml.tc60201.LdType;
import org.plcopen.xml.tc60201.PageSizeType;
import org.plcopen.xml.tc60201.SfcType;

/**
 * A sample validator interface for {@link org.plcopen.xml.tc60201.CoordinateInfoType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CoordinateInfoTypeValidator {
	boolean validate();

	boolean validatePageSize(PageSizeType value);
	boolean validateFbd(FbdType value);
	boolean validateLd(LdType value);
	boolean validateSfc(SfcType value);
}
