/**
 *
 * $Id$
 */
package org.plcopen.xml.tc60201.validation;

import java.math.BigDecimal;

import org.plcopen.xml.tc60201.FormattedText;

/**
 * A sample validator interface for {@link org.plcopen.xml.tc60201.InfoType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InfoTypeValidator {
	boolean validate();

	boolean validateDescription(FormattedText value);
	boolean validateName(String value);
	boolean validateVendor(String value);
	boolean validateVersion(BigDecimal value);
}
