/**
 *
 * $Id$
 */
package org.plcopen.xml.tc60201.validation;

import org.eclipse.emf.common.util.EList;

import org.plcopen.xml.tc60201.ActionsType;
import org.plcopen.xml.tc60201.AddData;
import org.plcopen.xml.tc60201.Body;
import org.plcopen.xml.tc60201.FormattedText;
import org.plcopen.xml.tc60201.InterfaceType;
import org.plcopen.xml.tc60201.PouType;
import org.plcopen.xml.tc60201.TransitionsType;

/**
 * A sample validator interface for {@link org.plcopen.xml.tc60201.PouType1}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PouType1Validator {
	boolean validate();

	boolean validateInterface(InterfaceType value);
	boolean validateActions(ActionsType value);
	boolean validateTransitions(TransitionsType value);
	boolean validateBody(EList<Body> value);
	boolean validateAddData(AddData value);
	boolean validateDocumentation(FormattedText value);
	boolean validateGlobalId(String value);
	boolean validateName(String value);
	boolean validatePouType(PouType value);
}
