/**
 *
 * $Id$
 */
package org.plcopen.xml.tc60201.validation;

import org.plcopen.xml.tc60201.AddData;
import org.plcopen.xml.tc60201.ContentHeaderType;
import org.plcopen.xml.tc60201.FileHeaderType;
import org.plcopen.xml.tc60201.FormattedText;
import org.plcopen.xml.tc60201.InstancesType;
import org.plcopen.xml.tc60201.TypesType;

/**
 * A sample validator interface for {@link org.plcopen.xml.tc60201.ProjectType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProjectTypeValidator {
	boolean validate();

	boolean validateFileHeader(FileHeaderType value);
	boolean validateContentHeader(ContentHeaderType value);
	boolean validateTypes(TypesType value);
	boolean validateInstances(InstancesType value);
	boolean validateAddData(AddData value);
	boolean validateDocumentation(FormattedText value);
	boolean validateProjectName(String value);
}
