/**
 *
 * $Id$
 */
package org.plcopen.xml.tc60201.validation;

import java.math.BigInteger;

import org.eclipse.emf.common.util.EList;

import org.plcopen.xml.tc60201.AddData;
import org.plcopen.xml.tc60201.FormattedText;
import org.plcopen.xml.tc60201.PouInstance;

/**
 * A sample validator interface for {@link org.plcopen.xml.tc60201.TaskType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TaskTypeValidator {
	boolean validate();

	boolean validatePouInstance(EList<PouInstance> value);
	boolean validateAddData(AddData value);
	boolean validateDocumentation(FormattedText value);
	boolean validateGlobalId(String value);
	boolean validateInterval(String value);
	boolean validateName(String value);
	boolean validatePriority(BigInteger value);
	boolean validateSingle(String value);
}
