/**
 *
 * $Id$
 */
package org.plcopen.xml.tc60201.validation;

import org.plcopen.xml.tc60201.ArrayValueType;
import org.plcopen.xml.tc60201.SimpleValueType;
import org.plcopen.xml.tc60201.StructValueType;

/**
 * A sample validator interface for {@link org.plcopen.xml.tc60201.Value}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ValueValidator {
	boolean validate();

	boolean validateSimpleValue(SimpleValueType value);
	boolean validateArrayValue(ArrayValueType value);
	boolean validateStructValue(StructValueType value);
}
