/**
 *
 * $Id$
 */
package org.plcopen.xml.tc60201.validation;

import org.eclipse.emf.common.util.EList;

import org.plcopen.xml.tc60201.AccessVariableType;
import org.plcopen.xml.tc60201.AddData;
import org.plcopen.xml.tc60201.FormattedText;

/**
 * A sample validator interface for {@link org.plcopen.xml.tc60201.VarListAccess}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VarListAccessValidator {
	boolean validate();

	boolean validateAccessVariable(EList<AccessVariableType> value);
	boolean validateAddData(AddData value);
	boolean validateDocumentation(FormattedText value);
}
